site_name: Islandora Workbench
site_dir: site
docs_dir: docs
site_description: Documentation for Islandora Workbench

dev_addr: 'localhost:8111'
repo_url: https://github.com/mjordan/islandora_workbench_docs

theme: readthedocs

nav:
  - Home: index.md
  - 'Requirements and installation': installation.md
  - Configuration: configuration.md
  - Checking configuration and input data: check.md
  - Creating nodes from the sample data: sample_data.md
  - Preparing your data: preparing_data.md
  - Field types: field_types.md
  - CSV file templates: csv_file_templates.md
  - Using Google Sheets as input data: google_sheets.md
  - CSV field templates: field_templates.md
  - Assigning URL aliases: aliases.md
  - Setting media types: media_types.md
  - Adding alt text to images: alt_text.md
  - Creating paged and compound content: paged_and_compound.md
  - Creating nodes without media: nodes_only.md
  - Creating nodes from files: creating_nodes_from_files.md
  - Rolling back nodes and media: rolling_back.md
  - Updating nodes: updating_nodes.md
  - Deleting nodes: deleting_nodes.md
  - Adding media to nodes: adding_media.md
  - Deleting media: deleting_media.md
  - The output CSV file: output_csv.md
  - Generating sample Islandora content: generating_sample_content.md
  - Logging: logging.md
